AllCops:
  Exclude:
    - 'bin/**/*'
    - 'spec/**/*'
    - 'vendor/**/*'

Lint/SafeNavigationChain:
  Enabled: true

Metrics/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/MethodLength:
  Max: 30

Style/BlockComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/Next:
  Enabled: false
